source "https://rubygems.org"

gem "rails", "~> 7.2.2", ">= 7.2.2.1"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false

# Auth
gem "devise"
gem "devise-jwt"
gem "bcrypt", "~> 3.1.7"

# CORS
gem "rack-cors"

# HTTP client for FuelIX
gem "faraday"
gem "faraday-multipart"

# PDF parsing
gem "pdf-reader"

# Background jobs
gem "sidekiq"

# Serialization
gem "oj"

# Pagination
gem "kaminari"

# Active Storage
gem "aws-sdk-s3", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails"
end
